#%RAML 1.0
title: Demo-sw-customer-papi
mediaType: 
- application/json
types:
 customers: !include /dataTypes/customers.raml
/customers:
 get:
  responses:
   200:
    body:
     type: array
     items: customers
 
 /{customerId}:
  get:
   responses:
     200:  
      body:
       type: customers      
     404:
     500:  
    
   
    
      
           
     