#%RAML 1.0
title: Demo-sw-customer-papi
mediaType: 
- application/json
types:
 customers: !include /dataTypes/customers.raml
 ErrorMessage: !include /dataTypes/ErrorMessage.raml
/customers:
 get:
  responses:
   200:
    body:
     type: array
     items: customers
   404:
   500: 
       body:
        type: ErrorMessage
 
 /{customerId}:
  get:
   responses:
     200:  
      body:
       type: customers      
     404:
      body:
       type: ErrorMessage 
     500: 
      body:
       type: ErrorMessage
  /{orderId}:  
      get:
   responses:
     200:  
      body: order      
     404:
      body:
       type: ErrorMessage 
     500: 
      body:
       type: ErrorMessage
    
      
           
     