#%RAML 1.0 NamedExample
value:

  customerId: 100
  fullName: SivaPrasad Valluru
  email: sivaprasad.valluru@gmail.com
  phone: 8088910831
  addresses: [
    "101,Samhitha Rainbow,vibgyor high school road,Bangalore,560066",
    "201,Samhitha Rainbow,vibgyor high school road,Bangalore,560066"
  ]
 